---
title: |
  ETC5543 Business Analytics Creative Activity 
  
  Project Report
date:  "`r format(Sys.time(), '%d %B, %Y')`"
author:
  - Xianghe XU 
  
team: Group 1
subtitle: |
  Department of Econometrics and Business Statistics

  Monash University
  
  | - 
  
  __An investigation report on performance of probability-based panels compared to other methods.__
  
  | -
abstract: "The aim of this report..."
header-includes: 
  - \renewcommand{\and}{\\ \\}
  - \AddToHook{env/abstract/before}{\vspace*{2cm}}
  - \makeatletter\AddToHook{cmd/@date/before}{\vspace*{2cm}}\makeatother
output:
  bookdown::pdf_document2:
    toc: FALSE
    number_sections: TRUE
  html_document: default


---
\newpage

\newpage
\tableofcontents
\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(haven)

dat <- haven::read_sav("../Data and survey materials/ACSSM Final Data_27-Feb-2023 weighted.sav")
```

```{r}
# dat %>% select(starts_with("TV_TIME")) %>% filter(TV_TIME_c == 6) %>% mutate("TOTAL" = TV_TIME_a+ TV_TIME_b+TV_TIME_c+ TV_TIME_d+ TV_TIME_e+ TV_TIME_f) %>% arrange(-TOTAL)
```


# Introduction and Motivation
(include the readings)

# Survey quality metrics

# Data Description

# Chanllenges
- Understand the metrics
- matching the metrics to variables

# Preliminary Analysis

# Analysis

# Limitation

# Summary

\newpage

# Reference

\newpage

# Appendix: All code for this report

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```

